project:
  type: website
  output-dir: docs

website:
  title: "Master of Science in Data Science (MSDS)" 
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - id: version-menu

  sidebar:
    style: floating
    collapse-level: 2
    search: true
    contents:
      - section: "Program Overview"
        contents:
          - introduction.qmd
          - calendar.qmd
          - structure.qmd
          - courses.qmd
          - research.qmd
      - section: "Policies and Conduct"
        contents:
          - policies.qmd
          - conduct.qmd
          - scholarship.qmd
      - section: "Resources and Support"
        contents:
          - advising.qmd
          - computing.qmd
          - wellness.qmd
          - international.qmd
          - graduation.qmd
      - section: "Appendix"
        contents:
          - contacts.qmd
          - faqs.qmd
          - glossary.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - css/version-menu.css
    js:
      - js/version-menu.js
    toc: true
    number-sections: true
