project:
  type: book
  output-dir: pdfs

book:
  title: "Master of Science in Data Science (MSDS)" 
  subtitle: "Student Handbook 2025"
  author: "Data Science Institute (DSI), University of Chicago"
  date: "Last Updated: April 28, 2025"
  chapters:
    - index.md
    - introduction.qmd
    - calendar.qmd
    - structure.qmd
    - courses.qmd
    - research.qmd
    - policies.qmd
    - conduct.qmd
    - scholarship.qmd
    - advising.qmd
    - computing.qmd
    - wellness.qmd
    - international.qmd
    - graduation.qmd
    - contacts.qmd
    - faqs.qmd
    - glossary.qmd

format:
  pdf:
    toc: true
    number-sections: true
    output-file: msds-handbook-2025.pdf
