project:
  type: website
  output-dir: docs

website:
  title: "Master of Science in Data Science (MSDS)" 
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Versions"
        id: version-menu

  sidebar:
    style: floating
    collapse-level: 2
    search: true
    contents:
      - section: "Program Overview"
        contents:
          - introduction.qmd
          - calendar.qmd
          - structure.qmd
          - courses.qmd
          - research.qmd
      - section: "Policies and Conduct"
        contents:
          - policies.qmd
          - conduct.qmd
          - scholarship.qmd
      - section: "Resources and Support"
        contents:
          - advising.qmd
          - computing.qmd
          - wellness.qmd
          - international.qmd
          - graduation.qmd
      - section: "Appendix"
        contents:
          - contacts.qmd
          - faqs.qmd
          - glossary.qmd

resources:
  - assets/js/version-menu.js

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - assets/css/styles.css
      - assets/css/version-menu.css
    # javascript:
      # - assets/js/version-menu.js
    toc: true
    number-sections: true
    # include-in-header: assets/js/version-menu.js
    include-before-body: assets/js/version-menu.js
    # include-after-body: assets/js/version-menu.js

meta:
  version: "2025"