project:
  type: website
  output-dir: docs

website:
  title: "Master of Science in Data Science (MSDS)" 
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Versions"
        menu:
          - text: "2025"
            href: /
          - text: "2024"
            href: /2024/

  sidebar:
    style: floating
    collapse-level: 2
    search: true
    contents:
      - section: "Program Overview"
        contents:
          - introduction.qmd
          - calendar.qmd
          - structure.qmd
          - courses.qmd
          - research.qmd
      - section: "Policies and Conduct"
        contents:
          - policies.qmd
          - conduct.qmd
      - section: "Resources and Support"
        contents:
          - computing.qmd
          - advising.qmd
          - wellness.qmd
          - international.qmd
          - opt-cpt.qmd
      - section: "Completion and Beyond"
        contents:
          - graduation.qmd
          - contacts.qmd
          - faqs.qmd
          - appendix.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    number-sections: true
