---
title: "Academic Calendar and Important Dates"
format: html
---


The MSDS program follows the University of Chicago’s quarter system. Students typically enroll in the Autumn, Winter, and Spring quarters, with some optional offerings in the Summer quarter.

## Quarterly Schedule

Students are expected to enroll in three courses per quarter to maintain full-time status. If you are enrolling LESS than OR MORE than three courses (300 units), please contact the program administrator or the program director immediately. International students are required to maintain full-time status (see [Office of International Affairs OIA](https://internationalaffairs.uchicago.edu) for details) with some exceptions. 

Important dates for each quarter, such as the start and end of classes, holidays, and exam periods, should be followed per the [University's academic calendar](https://www.uchicago.edu/en/education-and-research/academic-calendar) for the most up-to-date and official information.

## Key Deadlines

Students should adhere to the following important deadlines throughout the academic year:

- **Registration Deadlines**: Follow these [dates set by the university](https://registrar.uchicago.edu/calendars/registration-dates-deadlines/) by which students must complete course registration or submit changes. [Registration timeline and procedures](https://college.uchicago.edu/advising/registration) can also be found here.
- **Course Add/Drop Period**: Time frame in which students may adjust their course enrollments without penalty. 
  * Up to the end of the first week of class in any quarter, students can typically add or drop courses from their student portal, unless the course requires special permission. 
  * Up to the end of week three, students can still add, drop, or swap courses with instructors approval. The students affairs administrator will process these requests. 
  * After week three, dropping a course will result in a "W" on the transcript. You can drop/withdraw from a course up to Monday 5PM of week 9, or the day before the final exam/project due date, whichever is earlier. 
  * Switching from letter grade to pass/fail or vice versa also has deadline on the Monday of week 9, **and** requires instructor approval. Notice that pass/fail courses do not count towards MSDS degree requirements. 
- **Research Proposal Submission**: You should submit your research proposals to the director for approval as soon as it is conceptualized. This will ensure the scope and direction of the research is acceptable before you spend time on it. In any case, the proposal should be submitted before the Friday of week one of the quarter in which you plan to graduate. See [Research Project Requirement](research.qmd) for details.
- **Graduation Application**: Deadline for applying to graduate, generally is the first full week of the quarter you plan to graduate. See [Graduation and Beyond](graduation.qmd) for details. 



