---
title: "Frequently Asked Questions (FAQs)"
format: html
---

FAQs will be added throughout the year. These are not considered part of the official handbook but are provided as a convenient web resource for students.

## Enrollment and Registration

:::: {.callout .callout-question collapse=true}
### Q: Can I defer my admission (new student)?
**A:** Admission deferral requests are reviewed on a case-by-case basis. Please contact the MSDS program coordinator for guidance.
::::

:::: {.callout .callout-question collapse=true}
### Q: When will the Autumn class schedules be available?
**A:** Autumn 2025 graduate-level course schedules will be available by August 25. You can access them via the [UChicago Portal > Class Search](https://my.uchicago.edu).
::::

:::: {.callout .callout-question collapse=true}
### Q: When can I register for Autumn classes?
**A:** Incoming Autumn students can self-enroll starting September 22, 2025. Please follow [Physical Sciences Division (PSD) guidelines](https://physicalsciences.uchicago.edu/current-students/course-enrollment/) for course enrollments here.
::::

:::: {.callout .callout-question collapse=true}
### Q: I can't self-enroll in a course I’d like to take. What should I do?
**A:** Some courses have enrollment restrictions. You'll typically need approval from the instructor or their department. Once you obtain approval, forward the confirmation email to the MSDS program administrator, who can assist with registration.
::::

:::: {.callout .callout-question collapse=true}
### Q: What is the tuition rate?
**A:** Tuition and fees are published by the [Office of the Bursar](https://bursar.uchicago.edu/tuition-and-fees).
::::

:::: {.callout .callout-question collapse=true}
### Q: Can I take courses outside of the MSDS core and electives?
**A:** Yes. If you plan to take courses to count towards your degree, they must be approved by the MSDS Director. Also notice that some classes such as MSADS and MACS courses require special permission from the respective departments to enroll. 
::::

## Academic and Research Requirements

:::: {.callout .callout-question collapse=true}
### Q: Are there any Linear Algebra and math refresher courses availabe? 
**A:** Yes. You can consider using this [free course from Stanford University](https://stanford.edu/~shervine/teaching/cs-229/refresher-algebra-calculus). The University of Chicago Math Department also has a peer math tutoring services available to all students. You can find more information about the [math tutoring services here](https://mathematics.uchicago.edu/outreach/tutoring/).
::::

:::: {.callout .callout-question collapse=true}
### Q: Is there a GPA requirement in the program?
**A:** Yes. GPA requirements apply to academic standing, scholarship eligibility, and graduation. See [Policies and Conduct > Academic Policies](policies.qmd) and [Resources and Support > Graduation and Beyond](graduation.qmd) for details.
::::

:::: {.callout .callout-question collapse=true}
### Q: How can I find elective courses?
**A:** Graduate-level (300+ level) DATA, CMCS, and STAT courses that award a letter grade typically count as electives. Reading or research courses do not. For courses outside these departments, send the course syllabus to the MSDS Director for pre-approval before the quarter begins. If the upcoming syllabus isn’t yet available, a recent version from the same instructor may be used for temporary approval, pending submission of the final version.
::::

## Graduation and Commencement

:::: {.callout .callout-question collapse=true}
### Q: Do I need to apply to graduate? Can I withdraw the application if I change my mind?
**A:** Yes, you must apply to graduate, typically by the end of Week 1 of the quarter you plan to finish. You may withdraw your application without penalty by the end of Week 5. After Week 5, a fee may apply.
::::

:::: {.callout .callout-question collapse=true}
### Q: Can I participate in Convocation (graduation ceremony) if I finish early?
**A:** The University holds a Spring Convocation (usually in June), while the Physical Sciences Division (PSD) hosts an Autumn Graduation Reception (December) and a Spring MS Diploma Ceremony (June). If you are expected to complete your degree in Summer Quarter, you may still participate in the preceding Spring events.
::::

## Other Questions

:::: {.callout .callout-question collapse=true}
### Q: Do I have UChicago email access after graduation? 
**A:** Alum of UChicago will switch to their alumni email service afterwards. Your email address typically won't change. It can also be set as a forwarder. 
::::


:::: {.callout .callout-question collapse=true}
### Q: Are there travel funds for MSDS students to go to conferences or events? 
**A:** No, DSI does not have dedicated travel funds for MSDS students. Students planning to attend to conferences should contact their research mentors for potential funding. Some conferences also have travel grants available for students. There are also outside funding opportunities such as the [NSF Graduate Research Fellowship Program](https://www.nsfgrfp.org/) and the [AAAI Student Travel Grants](https://aaai.org/Conferences/AAAI-24/aaai24-student-travel-grants/).
::::
