---
title: "Graduation and Beyond"
format: html
---


Completing the MSDS program marks a significant achievement. This section outlines the steps for graduation and opportunities available to graduates post-completion.

## Graduation Procedures and Application

To graduate, students must:

- Complete all program requirements, including coursework and the research project.
- Minimum grade of each course, and a cumulative GPA requirement are described in the section "[Degree Completion Requirements](structure.qmd)".
- Follow the directions here from PSD to [apply for graduation](https://physicalsciences.uchicago.edu/current-students/graduation-and-degree-application/). (Make sure to update your expected graduation date - EGD - from the student portal first.)The deadline to submit is usually the **end of the first week in the quarter which you plan to graduate**. 

Students should review their academic progress with the MSDS director prior to applying to graduate.

## Convocation Ceremony

Graduating students are eligible to participate in the University of Chicago's annual convocation ceremony at the end of Spring Quarter each year.  Students graduating in Autumn and Winter quarters can expect to receive invitations to the convocation around March.

Details about regalia and scheduling are provided by the Physical Sciences Division Dean of Students Office in the months leading up to graduation.

Graduates can also request your diploma to be mailed to you. You can find more information about [ordering your diploma here](https://registrar.uchicago.edu/graduation/diplomas/). 

In addition to the University-wide events and the PSD-hosted events, DSI may also host additional events for MSDS graduates.

## For International Students

International students may need to apply for work authorization if they decide to seek employment in the US after graduation. The OPT application information can be found in the [International Students](international.qmd) section. 

## Alumni Engagement Opportunities

Graduates of the MSDS program are part of the broader University of Chicago alumni community. Benefits include:

- Continued access to career services
- Invitations to alumni networking events
- Participation in mentorship programs and industry panels

Alumni are encouraged to stay connected with the Data Science Institute and support future cohorts of MSDS students.

