---
title: "Master of Science in Data Science (MSDS)" 
subtitle: "MSDS Student Handbook 2026"
author: "Data Science Institute (DSI), University of Chicago"
date: "Last Updated: June 12, 2026"
format:
  html:
    number-sections: false
    toc: false
---

## Data Science Institute (DSI), University of Chicago
### Master's in Data Science (MSDS) - 2026  

To change to a different year/version of your matriculation, please use the dropdown menu on the top navigation bar above. This is the 2026 Autumn matriculation version.  

---

### 📥 Download the Handbook

You can download this full MSDS student handbook as a PDF:  
<a href="assets/pdfs/dsi_msds_handbook_2026.pdf" class="btn btn-primary" target="_blank" rel="noopener noreferrer"><strong>Download the 2026 MSDS Student Handbook</strong></a> 

### University of Chicago Student Manual

The [Student Manual](https://studentmanual.uchicago.edu/) is the official statement of University policies, regulations, and expected standards of student conduct that are applicable to all students. While students should be familiar with the manual as a whole, the following are commonly referenced by graduate students: 
[Student Life & Conduct](https://studentmanual.uchicago.edu/student-life-conduct/), [Leaves of Absence](https://studentmanual.uchicago.edu/academic-policies/voluntary-leaves-of-absence/), 
[University Grievance Policy for Graduate Students](https://studentmanual.uchicago.edu/university-policies/graduate-student-grievance-policy/), 
[Policy on Harassment, Discrimination, and Sexual Misconduct](https://studentmanual.uchicago.edu/university-policies/university-of-chicago-policy-on-harassment-discrimination-and-sexual-miscon/), 
[Policy on Title IX Sexual Harassment](https://studentmanual.uchicago.edu/university-policies/the-university-of-chicago-policy-on-title-ix-sexual-harassment/), 
[Policy on Religious Accommodation for Missed Classes, Assignments, and Exams](https://studentmanual.uchicago.edu/university-policies/policy-on-religious-accommodation-for-missed-classes-assignments-and-exams/), 
[Academic Honesty & Plagiarism](https://studentmanual.uchicago.edu/academic-policies/academic-honesty-plagiarism/), 
[Graduate Student Parent Policy](https://studentmanual.uchicago.edu/university-policies/graduate-student-parent-policy/). 


---

### About the Program

The Master's in Data Science (MSDS) program at the University of Chicago provides rigorous training in theoretical foundations, computational techniques, and research methodologies to prepare students for impactful careers and further study.

[Learn More About DSI](https://datascience.uchicago.edu) →

