---
title: "Research Project Requirement"
format: html
---

## Overview

All students enrolled in the Master of Science in Data Science (MSDS) program at the University of Chicago's Data Science Institute (DSI) are required to complete a rigorous research project. This project serves as a capstone experience, demonstrating mastery of data science techniques, the ability to conduct independent research, and effectively communicate results.

## Project Requirements

### Collaboration

- Students are encouraged to seek mentorship from faculty members or postdoctoral fellows within DSI. Projects can also involve faculty or researchers from other departments or institutions; however, such projects must include a DSI faculty supervisor or the MSDS Director to ensure proper guidance and oversight.
- In such projects with a faculty mentorship, it is possible that more than one MSDS student could be involved in the same project.
- Students who wish to conduct their own research can only do so with the approval of the MSDS Director. Such projects should not involve more than one MSDS student. There should be bi-weekly updates with the MSDS Director on the research progress.

### Project Approval

- All projects must receive formal approval from the MSDS Director to be eligible as fulfilling the MSDS program requirement.
- Students are encouraged to seek approval from the MSDS Director prior to initiation. This is absolutely necessary for students directing their own research. For students working with a faculty mentor, a formal proposal can be submitted at a later stage (but in any case, no later than the deadline of applying for graduation). Keep the MSDS Director informed of your current research collaborations even before the formal proposal submissions.
- For formal project approvals, students should submit a brief research proposal (1-2 pages) outlining their project's objective, methodology, data sources, expected outcomes, timeline, and supervising faculty member info (if applicable).

## Completion Options

Students must fulfill at least one of the following requirements to successfully complete their research project:

### Presentation to DSI Faculty Panel

- Deliver a 15-20 minute oral presentation followed by Q&A before a panel consisting of at least three DSI faculty members.
- The presentation should clearly outline the project's motivation, methodology, analysis, findings, and implications.

### Research Paper Submission

- Submit a comprehensive research paper.
- The paper should adhere to professional publication standards, clearly documenting the research problem, literature review, methods, data analysis, results, discussion, conclusions, and references.

### Peer-Reviewed Journal Publication

- Demonstrate acceptance or submission of research findings in a recognized peer-reviewed academic journal or conference proceeding relevant to data science. A statement of contribution and/or a faculty endorsement is also required.
- Documentation of submission or acceptance must be provided to the MSDS Director.
- The strength of the publication and the contribution from the student will be evaluated thoroughly to determine level of competency.

## Evaluation Criteria

Projects will be evaluated based on:

- Originality and innovation
- Rigorous application of data science methods
- Clarity of written and/or oral communication
- Depth of analysis and discussion
- Impact and practical significance

## Responsibilities

- **Students**: Manage project timelines, proactively engage with faculty mentors, and ensure adherence to guidelines.
- **Faculty Supervisors**: Provide consistent oversight, mentorship, and evaluation of the project.
- **MSDS Director**: Ensure program standards are maintained, provide final approval, and address any project-related issues.
