---
title: "Scholarships"
format: html
---

DSI offers merit-based scholarships to some of our admitted MSDS students. Scholarship award are for one year (3 quarters) with the student enrolling full-time, assuming the student takes three or more courses for each quarter (Autumn, Winter, and Spring). Otherwise, the scholarship could be adjusted or revoked.  


## Maintaining a High Standard

Students need to maintain in the previous (one) quarter a 3.0 GPA and all courses earning 'C' grade or above to continue receiving the scholarship award. Students under probation will lose the scholarship until the GPA and course grade requirements have been rectified in the following quarter. 

## Beyond the First Year

If a student is continuing to complete the program in their second year, they would be eligible for the same scholarship award, on a per-course/unit basis. The annual amount divided by 9 is the scholarship award per (100-unit) course the student will receive, up to three (100-unit) courses per quarter. 
