---
title: "Wellness"
format: html
---

Ensuring students' wellness is a top priority. The university has many resources to offer help and advice to students who need help themselves, as well as those seeking help for others around them.


## Wellness and Mental Health Resources

Wellness resources for the students themselves are available including:

- [Wellness programs](https://wellness.uchicago.edu/) 
  * [Mental Health and Counseling services](https://wellness.uchicago.edu/mental-health/)
  * [Workshops and Initiatives](https://wellness.uchicago.edu/healthy-living/wellness-programming/)
- [Campus and Student Life > Help](https://csl.uchicago.edu/get-help/medical-and-mental-health-services/)

Students are encouraged to utilize these services to maintain a healthy balance between academic responsibilities and personal well-being.


## UChicago CARES

The [Center For Awareness, Resolution, Education, and Support (CARES)](https://cares.uchicago.edu) allows anyone to file reports for themselves or on behalf of others whom might need help and support. This confidential and anonymous channel provides an alternative resource for the larger UChicago community. 


## Title IX Office

University of Chicago is a devoted community where every individual is respected, valued as autonomous, and treated equitably, without bias based on irrelevant personal characteristics.

The University is firmly committed to preventing, addressing, and, when necessary, disciplining instances of unlawful sexual harassment. 

We encourage anyone who believes they have experienced sexual misconduct to seek support, access medical care if needed, and report the incident to the [Title IX Coordinator for the University](https://equalopportunityprograms.uchicago.edu/contact-us/) as soon as possible.



